name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
         distribution: temurin
         java-version: '21'


      - name: Install dependencies
        run: npm install

      - name: Add Android platform
        run: npx cap add android
      - name: Build AdMob Bundle
        run: |
          npx esbuild www/admob.js --bundle --format=iife --platform=browser --outfile=www/admob.bundle.js

      - name: Sync Capacitor
        run: npx cap sync android
        
      - name: Configure AdMob
        run: |
          python3 - <<'PY'
                    PY

      - name: Add BHUR App Icon
        run: |
          mkdir -p android/app/src/main/res/drawable-nodpi
          cp ic_launcher.png android/app/src/main/res/drawable-nodpi/ic_launcher_custom.png

          python3 - <<'PY'
          from pathlib import Path

          manifest = Path("android/app/src/main/AndroidManifest.xml")
          text = manifest.read_text()

          text = text.replace(
              'android:icon="@mipmap/ic_launcher"',
              'android:icon="@drawable/ic_launcher_custom"'
          )

          text = text.replace(
              'android:roundIcon="@mipmap/ic_launcher_round"',
              'android:roundIcon="@drawable/ic_launcher_custom"'
          )

          manifest.write_text(text)
          PY

      - name: Configure AdMob
        run: |
          sed -i 's#</application>#        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="@string/admob_app_id" />\n    </application>#' android/app/src/main/AndroidManifest.xml
          sed -i 's#</resources>#    <string name="admob_app_id">ca-app-pub-9955317200878271~3605410882</string>\n</resources>#' android/app/src/main/res/values/strings.xml
      

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BHUR-TELANGA-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
